@echo off
echo ========================================
echo MCFax Python Files Sharing Script
echo ========================================
echo.
echo Creating SHARE folder and consolidating Python files by module...
echo.

REM Create the main SHARE directory
if not exist "SHARE" mkdir "SHARE"
echo Created SHARE directory

echo.
echo Copying and consolidating Python files...
echo.

REM Copy main.py (root level - unchanged)
if exist "main.py" (
    copy "main.py" "SHARE\main.py" >nul
    echo [✓] Copied main.py
) else (
    echo [✗] main.py not found
)

REM Create GUI module consolidated file
echo.
echo Creating gui.txt with all GUI module files...
echo # GUI Module Files > "SHARE\gui.txt"
echo # This file contains all Python files from the src/gui/ directory >> "SHARE\gui.txt"
echo # Generated by MCFax sharing script >> "SHARE\gui.txt"
echo. >> "SHARE\gui.txt"

if exist "src\gui\main_window.py" (
    echo # --- START OF FILE: main_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\main_window.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: main_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added main_window.py to gui.txt
) else (
    echo [✗] src\gui\main_window.py not found
)

if exist "src\gui\fax_job_window.py" (
    echo # --- START OF FILE: fax_job_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\fax_job_window.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: fax_job_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added fax_job_window.py to gui.txt
) else (
    echo [✗] src\gui\fax_job_window.py not found
)

if exist "src\gui\contact_window.py" (
    echo # --- START OF FILE: contact_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\contact_window.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: contact_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added contact_window.py to gui.txt
) else (
    echo [✗] src\gui\contact_window.py not found
)

if exist "src\gui\fax_history_window.py" (
    echo # --- START OF FILE: fax_history_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\fax_history_window.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: fax_history_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added fax_history_window.py to gui.txt
) else (
    echo [✗] src\gui\fax_history_window.py not found
)

if exist "src\gui\settings_window.py" (
    echo # --- START OF FILE: settings_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\settings_window.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: settings_window.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added settings_window.py to gui.txt
) else (
    echo [✗] src\gui\settings_window.py not found
)

if exist "src\gui\integrated_pdf_viewer.py" (
    echo # --- START OF FILE: integrated_pdf_viewer.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\integrated_pdf_viewer.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: integrated_pdf_viewer.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added integrated_pdf_viewer.py to gui.txt
) else (
    echo [✗] src\gui\integrated_pdf_viewer.py not found
)

if exist "src\gui\progress_button.py" (
    echo # --- START OF FILE: progress_button.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\progress_button.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: progress_button.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added progress_button.py to gui.txt
) else (
    echo [✗] src\gui\progress_button.py not found
)

if exist "src\gui\__init__.py" (
    echo # --- START OF FILE: __init__.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    type "src\gui\__init__.py" >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo # --- END OF FILE: __init__.py --- >> "SHARE\gui.txt"
    echo. >> "SHARE\gui.txt"
    echo [✓] Added __init__.py to gui.txt
) else (
    echo [✗] src\gui\__init__.py not found
)

REM Create Core module consolidated file
echo.
echo Creating core.txt with all Core module files...
echo # Core Module Files > "SHARE\core.txt"
echo # This file contains all Python files from the src/core/ directory >> "SHARE\core.txt"
echo # Generated by MCFax sharing script >> "SHARE\core.txt"
echo. >> "SHARE\core.txt"

if exist "src\core\settings_portable.py" (
    echo # --- START OF FILE: settings_portable.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    type "src\core\settings_portable.py" >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo # --- END OF FILE: settings_portable.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo [✓] Added settings_portable.py to core.txt
) else (
    echo [✗] src\core\settings_portable.py not found
)

if exist "src\core\folder_watcher.py" (
    echo # --- START OF FILE: folder_watcher.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    type "src\core\folder_watcher.py" >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo # --- END OF FILE: folder_watcher.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo [✓] Added folder_watcher.py to core.txt
) else (
    echo [✗] src\core\folder_watcher.py not found
)

if exist "src\core\settings.py" (
    echo # --- START OF FILE: settings.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    type "src\core\settings.py" >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo # --- END OF FILE: settings.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo [✓] Added settings.py to core.txt
) else (
    echo [✗] src\core\settings.py not found
)

if exist "src\core\__init__.py" (
    echo # --- START OF FILE: __init__.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    type "src\core\__init__.py" >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo # --- END OF FILE: __init__.py --- >> "SHARE\core.txt"
    echo. >> "SHARE\core.txt"
    echo [✓] Added __init__.py to core.txt
) else (
    echo [✗] src\core\__init__.py not found
)

REM Create Database module consolidated file
echo.
echo Creating database.txt with all Database module files...
echo # Database Module Files > "SHARE\database.txt"
echo # This file contains all Python files from the src/database/ directory >> "SHARE\database.txt"
echo # Generated by MCFax sharing script >> "SHARE\database.txt"
echo. >> "SHARE\database.txt"

if exist "src\database\connection.py" (
    echo # --- START OF FILE: connection.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    type "src\database\connection.py" >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo # --- END OF FILE: connection.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo [✓] Added connection.py to database.txt
) else (
    echo [✗] src\database\connection.py not found
)

if exist "src\database\models.py" (
    echo # --- START OF FILE: models.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    type "src\database\models.py" >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo # --- END OF FILE: models.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo [✓] Added models.py to database.txt
) else (
    echo [✗] src\database\models.py not found
)

if exist "src\database\schema.py" (
    echo # --- START OF FILE: schema.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    type "src\database\schema.py" >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo # --- END OF FILE: schema.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo [✓] Added schema.py to database.txt
) else (
    echo [✗] src\database\schema.py not found
)

if exist "src\database\__init__.py" (
    echo # --- START OF FILE: __init__.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    type "src\database\__init__.py" >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo # --- END OF FILE: __init__.py --- >> "SHARE\database.txt"
    echo. >> "SHARE\database.txt"
    echo [✓] Added __init__.py to database.txt
) else (
    echo [✗] src\database\__init__.py not found
)

REM Create PDF module consolidated file
echo.
echo Creating pdf.txt with all PDF module files...
echo # PDF Module Files > "SHARE\pdf.txt"
echo # This file contains all Python files from the src/pdf/ directory >> "SHARE\pdf.txt"
echo # Generated by MCFax sharing script >> "SHARE\pdf.txt"
echo. >> "SHARE\pdf.txt"

if exist "src\pdf\pdf_browser.py" (
    echo # --- START OF FILE: pdf_browser.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\pdf_browser.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: pdf_browser.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added pdf_browser.py to pdf.txt
) else (
    echo [✗] src\pdf\pdf_browser.py not found
)

if exist "src\pdf\pdf_viewer.py" (
    echo # --- START OF FILE: pdf_viewer.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\pdf_viewer.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: pdf_viewer.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added pdf_viewer.py to pdf.txt
) else (
    echo [✗] src\pdf\pdf_viewer.py not found
)

if exist "src\pdf\pdf_editor.py" (
    echo # --- START OF FILE: pdf_editor.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\pdf_editor.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: pdf_editor.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added pdf_editor.py to pdf.txt
) else (
    echo [✗] src\pdf\pdf_editor.py not found
)

if exist "src\pdf\pdf_processor.py" (
    echo # --- START OF FILE: pdf_processor.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\pdf_processor.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: pdf_processor.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added pdf_processor.py to pdf.txt
) else (
    echo [✗] src\pdf\pdf_processor.py not found
)

if exist "src\pdf\cover_page.py" (
    echo # --- START OF FILE: cover_page.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\cover_page.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: cover_page.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added cover_page.py to pdf.txt
) else (
    echo [✗] src\pdf\cover_page.py not found
)

if exist "src\pdf\__init__.py" (
    echo # --- START OF FILE: __init__.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    type "src\pdf\__init__.py" >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo # --- END OF FILE: __init__.py --- >> "SHARE\pdf.txt"
    echo. >> "SHARE\pdf.txt"
    echo [✓] Added __init__.py to pdf.txt
) else (
    echo [✗] src\pdf\__init__.py not found
)

REM Create Fax module consolidated file
echo.
echo Creating fax.txt with all Fax module files...
echo # Fax Module Files > "SHARE\fax.txt"
echo # This file contains all Python files from the src/fax/ directory >> "SHARE\fax.txt"
echo # Generated by MCFax sharing script >> "SHARE\fax.txt"
echo. >> "SHARE\fax.txt"

if exist "src\fax\xml_generator.py" (
    echo # --- START OF FILE: xml_generator.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    type "src\fax\xml_generator.py" >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo # --- END OF FILE: xml_generator.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo [✓] Added xml_generator.py to fax.txt
) else (
    echo [✗] src\fax\xml_generator.py not found
)

if exist "src\fax\faxfinder_api.py" (
    echo # --- START OF FILE: faxfinder_api.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    type "src\fax\faxfinder_api.py" >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo # --- END OF FILE: faxfinder_api.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo [✓] Added faxfinder_api.py to fax.txt
) else (
    echo [✗] src\fax\faxfinder_api.py not found
)

if exist "src\fax\__init__.py" (
    echo # --- START OF FILE: __init__.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    type "src\fax\__init__.py" >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo # --- END OF FILE: __init__.py --- >> "SHARE\fax.txt"
    echo. >> "SHARE\fax.txt"
    echo [✓] Added __init__.py to fax.txt
) else (
    echo [✗] src\fax\__init__.py not found
)

echo.
echo ========================================
echo Copy operation completed!
echo ========================================
echo.
echo Summary:
echo - Created SHARE folder with consolidated module files
echo - main.py (unchanged)
echo - gui.txt (8 GUI module files consolidated)
echo - core.txt (4 Core module files consolidated)
echo - database.txt (4 Database module files consolidated)
echo - pdf.txt (6 PDF module files consolidated)
echo - fax.txt (3 Fax module files consolidated)
echo.
echo Total: 6 files containing all 26 Python source files
echo Each .txt file contains multiple Python files with clear delimiters
echo.
echo You can now share the SHARE folder contents.
echo.
pause
